apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.serviceName}}-config
data:
  {{.Values.serviceName}}-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:{{.Values.application.port.http}}
    extensions:
      # Enable the Google Client auth extension for use.
      googleclientauth:
      # Used for the K8S health probes.
      health_check:
        endpoint: "0.0.0.0:{{.Values.health.port}}"
        path: "{{.Values.health.basePath}}"
    processors:
      # The batch processor controls how much data to export and when it will be exported.
      batch:
        send_batch_max_size: 0
        send_batch_size: 8192
        timeout: 200ms
      # The filters to apply to the Trace data.
      {{- range $key, $value := .Values.application.filter.rule}}
      filter/spans_wout_{{snakecase $key}}:
        error_mode: ignore
        traces:
          span:
            - 'resource.attributes["{{snakecase $key | replace "_" "."}}"] == nil'
            - 'IsMatch(resource.attributes["{{snakecase $key | replace "_" "."}}"], "{{$value}}") == false'
          spanevent:
            - 'res
