apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}-http-service
  labels:
    app.kubernetes.io/component: {{.Values.labels.k8sComponent}}
    app.kubernetes.io/instance: {{.Release.Service}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    app.kubernetes.io/name: {{.Values.serviceName}}
    app.kubernetes.io/part-of: {{.Values.labels.k8sSystem}}
    app.kubernetes.io/version: {{.Chart.AppVersion}}
    helm.sh/chart: {{include "obs-trace-gw.chart" .}}
spec:
  selector:
    app.kubernetes.io/name: {{.Values.serviceName}}
  ports:
    - protocol: TCP
      port: {{.Values.application.port.http}}
      name: http
  type: NodePort
