destination:
  googleCloud:
    traceEndpoint: https://telemetry.googleapis.com/v1/traces

environment:
  cloudProvider: cloud-citi-andromeda
  cloudRegion: NAM
  name: DEV

hardwareResource:
  cpuLimit: 300m
  cpuRequest: 75m
  ramLimit: 512Mi
  ramRequest: 256Mi

logging:
  level: DEBUG
  encoding: json
  outputPaths:
    - stdout
  errorOutputPaths:
    - stdout
  sampling:
    enabled: true
    initial: 100
    thereafter: 100

exporter:
  debug:
    enabled: true
    verbosity: detailed
    initialSampleCount: 5
    sampleFrequency: 10
